FROM ubuntu:gecode
MAINTAINER Vincent Vigneron <vigneron@info.univ-angers.fr>
RUN cd bin && wget https://sites.google.com/site/cp4spm/GSPMCP && chmod a+x GSPMCP && cd .. && mkdir data && mkdir results
